version: '3'

services:

  postgres:
    image: postgres:12
    restart: on-failure
    volumes:
      - postgres-quarkus-data:/var/lib/postgresql/data/
      - ./.docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: test,local
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
#    # TODO: to log all queries...
#    command: ["postgres", "-c", "log_statement=all"]


volumes:
  postgres-quarkus-data:
